"adding circleci config"

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,4 @@
-env_vars: &env_vars
+default_env_vars: &default_env_vars
     JAVA_HOME: /usr/local/openjdk8u154-cassandra-b02
     ANT_HOME: /usr/local/apache-ant-1.10.1
     LANG: en_US.UTF-8
@@ -14,16 +14,55 @@ env_vars: &env_vars
     PYTHONUNBUFFERED: true
     CASS_DRIVER_NO_EXTENSIONS: true
     CASS_DRIVER_NO_CYTHON: true
-    CCM_MAX_HEAP_SIZE: 3072M
+    CCM_MAX_HEAP_SIZE: 1024M
     CCM_HEAP_NEWSIZE: 256M
+# For environments with xlarge instances, use more memory
+high_capacity_env_vars: &high_capacity_env_vars
+    <<: *default_env_vars
+    CCM_MAX_HEAP_SIZE: 3072M
+# Settings for users who do not have a paid CircleCI account
+default_env_settings: &default_env_settings
+    resource_class: medium
+    parallelism: 4
+# Settings for users with high-capacity, paid CircleCI account
+high_capacity_env_settings: &high_capacity_env_settings
+    resource_class: xlarge
+    parallelism: 90
+default_jobs: &default_jobs
+        jobs:
+            - build
+            - unit_tests:
+                  requires:
+                      - build
+with_dtests_jobs: &with_dtest_jobs 
+        jobs:
+            - build
+            - unit_tests:
+                  requires:
+                      - build
+            - dtests:
+                  requires:
+                      - unit_tests
+# Set env_settings, env_vars, and workflows/build_and_run_tests based on environment
+env_settings: &env_settings
+    # <<: *default_env_settings
+    <<: *high_capacity_env_settings
+env_vars: &env_vars
+    # <<: *default_env_vars
+    <<: *high_capacity_env_vars
+workflows:
+    version: 2
+    # build_and_run_tests: *default_jobs
+    build_and_run_tests: *with_dtest_jobs
 version: 2
 jobs:
   build:
-    resource_class: xlarge
+    <<: *env_settings
+    parallelism: 1 # This job doesn't benefit from parallelism
     working_directory: ~/
     shell: /bin/bash -eo pipefail -l
     docker:
-      - image: kjellman/cassandra-test:0.1.2
+      - image: kjellman/cassandra-test:0.1.3
         environment:
             <<: *env_vars
     steps:
@@ -78,8 +117,7 @@ jobs:
                 - cassandra
                 - .m2
   unit_tests:
-    resource_class: xlarge
-    parallelism: 100
+    <<: *env_settings
     working_directory: ~/
     shell: /bin/bash -eo pipefail -l
     docker:
@@ -128,8 +166,7 @@ jobs:
           path: ~/cassandra/build/test/logs
           destination: logs
   dtests:
-    resource_class: xlarge
-    parallelism: 100
+    <<: *env_settings
     working_directory: ~/
     shell: /bin/bash -eo pipefail -l
     docker:
@@ -143,7 +180,7 @@ jobs:
           name: Clone Cassandra dtest Repository (via git)
           command: |
             export LANG=en_US.UTF-8
-            git clone --single-branch --depth 1 git://github.com/jasobrown/cassandra-dtest.git ~/cassandra-dtest
+            git clone --single-branch --depth 1 git://github.com/mkjellman/cassandra-dtest.git ~/cassandra-dtest
       - run:
           name: Configure virtualenv and python Dependencies
           command: |
@@ -205,6 +242,7 @@ jobs:
 
             source ~/env/bin/activate
             export PATH=$PATH:$ANT_HOME/bin:$JAVA_HOME/bin
+            export IP_PREFIX="127.0.${CIRCLE_NODE_INDEX}."
 
             cd ~/cassandra-dtest
             mkdir -p /tmp/dtest
@@ -222,17 +260,21 @@ jobs:
           name: Run dtests (without vnodes)
           no_output_timeout: 30m
           command: |
-            source ~/env/bin/activate
-            export PATH=$PATH:$ANT_HOME/bin:$JAVA_HOME/bin
+            # for now require at least 50 circleci containers to run the dtests (with less resources the tests won't produce reliable results or will fail to complete) 
+            if [ $CIRCLE_NODE_TOTAL -gt 50 ]; then
+                source ~/env/bin/activate
+                export PATH=$PATH:$ANT_HOME/bin:$JAVA_HOME/bin
 
-            cd ~/cassandra-dtest
-            export TEST_TAG="novnodes"
-            ./run_dtests.py --vnodes false --nose-options="--verbosity=3 --with-dtestxunit --nocapture --attr=!resource-intensive" `cat /tmp/novnode_python_tests_final.txt` 2>&1 | tee /tmp/dtest/stdout-novnodes.txt || true
+                cd ~/cassandra-dtest
+                export TEST_TAG="novnodes"
+                export IP_PREFIX="127.0.${CIRCLE_NODE_INDEX}."
+                ./run_dtests.py --vnodes false --nose-options="--verbosity=3 --with-dtestxunit --nocapture --attr=!resource-intensive" `cat /tmp/novnode_python_tests_final.txt` 2>&1 | tee /tmp/dtest/stdout-novnodes.txt || true
 
-            # store the test results somewhere where we can pick them up
-            mv nosetests.xml nosetests-novnode.xml
-            mkdir -p /tmp/results/ || true
-            find ~/cassandra-dtest/ -name "*.xml" -exec cp {} /tmp/results/ \; 
+                # store the test results somewhere where we can pick them up
+                mv nosetests.xml nosetests-novnode.xml
+                mkdir -p /tmp/results/ || true
+                find ~/cassandra-dtest/ -name "*.xml" -exec cp {} /tmp/results/ \; 
+            fi
       - store_test_results:
           path: /tmp/results/
       - store_artifacts:
@@ -241,14 +283,3 @@ jobs:
       - store_artifacts:
           path: ~/cassandra-dtest/logs
           destination: dtest_logs
-workflows:
-    version: 2
-    build_and_run_tests:
-        jobs:
-            - build
-            - unit_tests:
-                  requires:
-                      - build
-            - dtests:
-                  requires:
-                      - unit_tests
